### ISSUE TITLE
Replay is bugged in certain games

### ISSUE THREAD

**Issue by Roadrunner191919** [boardgamers/gaia-project#158] opened 2021-08-10 13:14 UTC
https://www.boardgamers.space/game/Pink-redundancy-941

I tried viewing this game's replay and it stopped after 52/432 in the replay bar. Nothing happened after that, it went to 53,54,55... but there was no movement on the map or in the log. This has happened previously in some games, one such game is https://www.boardgamers.space/game/Telling-secretary-320 

In the second link, it stops in the 90's (94/190 or something if I remember right).

**Comment by zeitlinger** [comment] 2021-08-16 06:24
looks like this is the line that breaks: 

`"taklons  burn 2. action power3. (2/4,B/0/0 ⇒ 3,B/1/0/0)",`

@coyotte508 do you have an idea how to fix / or reproduce this locally.

[This](https://github.com/boardgamers/gaia-project/commit/c5d2931c9fcb1418af1e73c273324d94882f34e5#diff-6823ba291208e97939fc0da7ee463e1e39b7656509a5f1a824c697bc87a9a481R914) doesn't seem to do the trick.

**Comment by coyotte508** [comment] 2021-08-16 07:23
Maybe:

```ts
  move(_move: string, allowIncomplete = true) {
    assert(this.newTurn, "Cannot execute a move after executing an incomplete move");

    // add this
    _move = _move.replace(/\s\([^)]+\)/g, '')
```

**Comment by zeitlinger** [comment] 2021-08-16 07:29
good idea - do you have an idea how to test replay locally?

**Comment by coyotte508** [comment] 2021-08-16 08:04
I guess in `Wrapper.vue` you could add overlay buttons that do :

- store.dispatch("gaiaViewer/replayStart");
- store.dispatch("gaiaViewer/replayTo", info);
- store.dispatch("gaiaViewer/replayEnd");

**Comment by zeitlinger** [comment] 2021-08-16 18:56
can't seem to get it to work

```
Index: viewer/src/components/Wrapper.vue
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/viewer/src/components/Wrapper.vue b/viewer/src/components/Wrapper.vue
--- a/viewer/src/components/Wrapper.vue	(revision Staged)
+++ b/viewer/src/components/Wrapper.vue	(date 1629140113841)
@@ -4,42 +4,80 @@
     <b-modal v-model="modalShow" size="lg" @ok="handleOK" title="Load from JSON">
       <b-textarea v-model="text" rows="6" />
     </b-modal>
-    <b-avatar
-      button
-      style="position: fixed; left: 20px; bottom: 20px; z-index: 100"
-      size="50"
-      @click="modalShow = true"
-    >
-      LOAD
-    </b-avatar>
-    <b-avatar button style="position: fixed; left: 80px; bottom: 20px; z-index: 100" size="50" @click="openExport">
-      EXPORT
-    </b-avatar>
+    <div class="d-flex">
+      <b-button-group>
+        <b-button @click="modalShow = true">Load</b-button>
+        <b-button @click="openExport">Export</b-button>
+      </b-button-group>
+      <div class="mt-75">
+        <b-btn variant="info" size="sm" @click="startReplay" v-if="!replayData">Replay</b-btn>
+        <div v-else class="d-flex align-items-center">
+          <b-btn size="sm" class="mr-1" @click="replayTo(replayData.start)"><b-icon icon="skip-backward-fill" /></b-btn>
+          <b-btn size="sm" class="mx-1" @click="replayTo(Math.max(replayData.start, replayData.current - 1))"
+            ><b-icon icon="skip-start-fill"
+          /></b-btn>
+          <span
+            class="mx-1 text-center"
+            style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap; flex-grow: 1"
+          >
+            {{ replayData.current }} / {{ replayData.end }}
+          </span>
+          <b-btn size="sm" class="mx-1" @click="replayTo(Math.min(replayData.end, replayData.current + 1))"
+            ><b-icon icon="skip-end-fill"
+          /></b-btn>
+          <b-btn size="sm" class="mx-1" @click="replayTo(replayData.end)"><b-icon icon="skip-forward-fill" /></b-btn>
+          <b-btn size="sm" class="ml-1" @click="endReplay"><b-icon icon="stop-fill" variant="danger" /></b-btn>
+        </div>
+      </div>
+    </div>
   </div>
 </template>
 <script lang="ts">
-import { Vue, Prop, Watch, Component } from "vue-property-decorator";
+import { Component, Vue } from "vue-property-decorator";
 import Game from "./Game.vue";
+import { UndoPropagation } from "../logic/commands";
 
 @Component({
-  components: { Game }
+  components: { Game },
 })
 export default class Wrapper extends Vue {
   modalShow = false;
   text = "";
+  replayData: { stard: number; end: number; current: number } | null;
 
-  handleOK () {
+  handleOK() {
     this.$store.dispatch("gaiaViewer/loadFromJSON", JSON.parse(this.text));
   }
 
-  openExport () {
+  openExport() {
     this.text = JSON.stringify(this.$store.state.gaiaViewer.data);
     this.modalShow = true;
   }
+
+  startReplay() {
+    this.$store.dispatch("gaiaViewer/replayStart");
+  }
+
+  replayTo(dest: number) {
+    this.$store.dispatch("gaiaViewer/replayTo", dest);
+  }
+
+  endReplay() {
+    this.$store.dispatch("gaiaViewer/replayEnd");
+  }
+
+  mounted() {
+      const unsub = this.$store.subscribeAction(({ type, payload }) => {
+        if (type === "replay:info") {
+          this.replayData = payload;
+        }
+      });
+      this.$on("hook:beforeDestroy", () => unsub());
+    }
 }
 </script>
-<style lang="scss">
-.b-avatar-custom {
-  display: contents !important;
+<style lang="scss" scoped>
+.btn-group {
+  margin: .3rem;
 }
 </style>
```

**Comment by coyotte508** [comment] 2021-08-17 18:17
I pushed a commit.

**Comment by zeitlinger** [comment] 2021-08-17 19:47
strangely the local replay works just fine - maybe the issue got fixed in the meantime?

**Closed** 2021-08-17 20:18 UTC

**Comment by zeitlinger** [comment] 2021-08-17 20:56
@Roadrunner191919 not sure why - but it's working now :smile:
